### ISSUE TITLE
add a way to download the corrupted svg (and make the pngs higher quality)

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [x8BitRain/svg-emoji-corrupt#19]
notice: images taken in earlier version, may not be accurate (besides the first one)
![2corrupted](https://github.com/user-attachments/assets/f35fd80e-4d5e-4717-911d-8b0a02d3138f)
![corrupted](https://github.com/user-attachments/assets/1441ec5d-95fa-4d90-8260-fa7a9420d047)
![youtube but awesome](https://github.com/user-attachments/assets/a738c623-d76f-487d-8d32-bf5a97663df9)

**Comment by x8BitRain** [comment]
Done 👍
